#!/usr/bin/env bash

# Edit those two
IN_GAME_LAYOUT="us"
IN_GAME_VARIANT=""

DEFAULT_LAYOUT=$(setxkbmap -query | grep layout | awk '{print $2}')
DEFAULT_VARIANT=$(setxkbmap -query | grep variant | awk '{print $2}')

echo "$DEFAULT_LAYOUT"

setxkbmap "$IN_GAME_LAYOUT" "$IN_GAME_VARIANT"
"$@"
setxkbmap "$DEFAULT_LAYOUT" "$DEFAULT_VARIANT"
