#!/usr/bin/env bash

# x11 | sway
ENV="x11"

GAME_LAYOUT="us"
GAME_VARIANT=""

DEFAULT_LAYOUT="fr"
DEFAULT_VARIANT="bepo_afnor"

if [[ "$ENV" == "x11" ]]; then
  setxkbmap "$GAME_LAYOUT" "$GAME_VARIANT"
  "$@"
  setxkbmap "$DEFAULT_LAYOUT" "$DEFAULT_VARIANT"
fi

if [[ "$ENV" == "sway" ]]; then
  input type:keyboard xkb_layout "$GAME_LAYOUT"
  input type:keyboard xkb_variant "$GAME_VARIANT"
  "$@"
  input type:keyboard xkb_layout "$DEFAULT_LAYOUT"
  input type:keyboard xkb_layout "$DEFAULT_VARIANT"
fi
